In [1]:
import findspark
findspark.init()

import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
spark = SparkSession.builder.appName('Script-5 namespace pct cost').getOrCreate()
spark

In [2]:
path_az_cost = "C:\\Motorola\\AzureCost Data/"
path_usage = "C:\\Motorola\\UsageData/"

In [3]:
schm = StructType([
    StructField("agmbgm",StringType(),True),
    StructField("business_unit",StringType(),True),
    StructField("dateTime",TimestampType(),True),
    StructField("chargetype",StringType(),True),
    StructField("cluster_cost",BooleanType(),True),
    StructField("cost",DoubleType(),True),
    StructField("cost_location",StringType(),True),
    StructField("currency",StringType(),True),
    StructField("departmentCode",StringType(),True),
    StructField("environment",StringType(),True),
    StructField("exec_owner",StringType(),True),
    StructField("finance_owner",StringType(),True),
    StructField("friendly_name",StringType(),True),
    StructField("globally_shared",BooleanType(),True),
    StructField("is_cie_project",BooleanType(),True),
    StructField("meter",StringType(),True),
    StructField("meter_subcategory",StringType(),True),
    StructField("pricingmodel",StringType(),True),
    StructField("product",StringType(),True),
    StructField("product_owner",StringType(),True),
    StructField("project_name",StringType(),True),
    StructField("res_name",StringType(),True),
    StructField("resource_group",StringType(),True),
    StructField("run_date",StringType(),True),
    StructField("service_name",StringType(),True),
    StructField("service_tier",StringType(),True),
    StructField("sleeve",StringType(),True),
    StructField("unique_id",LongType(),True),
    StructField("to_date",IntegerType(),True),
    StructField("to_hour",IntegerType(),True)
    
    
])

reading cost data

In [4]:
df_az_cost = spark.read.csv(path_az_cost + "AzureCost220401.csv",schema = schm)

finding cost per environment

In [8]:
df_env_cost = df_az_cost.filter(df_az_cost.environment == "US Commercial Dev EastUS").filter(df_az_cost.cluster_cost==True).groupBy('environment').agg(sum("cost").alias('env_cost'))

cost for Dev EastUS

In [9]:
df_env_cost = df_env_cost.withColumnRenamed("environment","environment_name")

In [10]:
df_env_cost.toPandas()

           environment_name    env_cost
0  US Commercial Dev EastUS  854.273649

In [11]:
scm = StructType([
    StructField("namespace",StringType(),True),
    StructField("timestamp",StringType(),True),
    StructField("kubernetes_pod_name_keyword",StringType(),True),
    StructField("kubernetes_pod_cpu_usage_node_pct",DoubleType(),True),
    StructField("kubernetes_container_cpu_limit_cores",DoubleType(),True),
    StructField("kubernetes_container_cpu_request_cores",DoubleType(),True),
    StructField("kubernetes_pod_cpu_usage_limit_pct",DoubleType(),True),
    StructField("kubernetes_pod_memory_usage_bytes",DoubleType(),True),
    StructField("kubernetes_pod_cpu_usage_nanocores",DoubleType(),True),
    StructField("key",StringType(),True),
    StructField("environment_name",StringType(),True),
    StructField("to_date",IntegerType(),True)
])

reading Usage Data

In [12]:
df = spark.read.csv(path_usage+'UsageDevEastus220401.csv',inferSchema=True,header=True,schema=scm)

In [13]:
df.toPandas()

,namespace,timestamp,kubernetes_pod_name_keyword,kubernetes_pod_cpu_usage_node_pct,kubernetes_container_cpu_limit_cores,kubernetes_container_cpu_request_cores,kubernetes_pod_cpu_usage_limit_pct,kubernetes_pod_memory_usage_bytes,kubernetes_pod_cpu_usage_nanocores,key,environment_name,to_date
0,accnext-dev,2022-04-01 00:05:00,test-msivms-core-0-899f44fb7-dfhc2,0.005914,2.0,0.1,0.047314,734756864.0,378509787.0,accnext-dev_test-msivms-core-0-899f44fb7-dfhc2...,US Commercial Dev EastUS,20220401.0
1,accnext-dev,2022-04-01 00:10:00,test-msivms-core-0-899f44fb7-dfhc2,0.000410,2.0,0.1,0.004377,643936256.0,26261015.0,accnext-dev_test-msivms-core-0-899f44fb7-dfhc2...,US Commercial Dev EastUS,20220401.0
2,accnext-dev,2022-04-01 00:15:00,test-msivms-core-0-899f44fb7-dfhc2,0.000418,2.0,0.1,0.004461,644014080.0,26766923.0,accnext-dev_test-msivms-core-0-899f44fb7-dfhc2...,US Commercial Dev EastUS,20220401.0
3,accnext-dev,2022-04-01 00:20:00,test-msivms-core-0-899f44fb7-dfhc2,0.000398,2.0,0.1,0.004245,643833856.0,25468170.0,accnext-dev_test-msivms-core-0-899f44fb7-dfhc2...,US Commercial Dev EastUS,20220401.0
4,accnext-dev,2022-04-01 00:25:00,test-msivms-core-0-899f44fb7-dfhc2,0.000420,2.0,0.1,0.004479,644177920.0,26875924.0,accnext-dev_test-msivms-core-0-899f44fb7-dfhc2...,US Commercial Dev EastUS,20220401.0
...,...,...,...,...,...,...,...,...,...,...,...,...
863573,location-service-dev,2022-04-01 21:00:00,location-admin-uimaster-regression-69785b9b58-...,0.000000,0.0,0.0,0.000000,53710848.0,411745.0,location-service-dev_location-admin-uimaster-r...,US Commercial Dev EastUS,20220401.0
863574,location-service-dev,2022-04-01 21:05:00,location-admin-uimaster-regression-69785b9b58-...,0.000000,0.0,0.0,0.000000,53616640.0,233815.0,location-service-dev_location-admin-uimaster-r...,US Commercial Dev EastUS,20220401.0
863575,location-service-dev,2022-04-01 21:10:00,location-admin-uimaster-regression-69785b9b58-...,0.000000,0.0,0.0,0.000000,53633024.0,108390.0,location-service-dev_location-admin-uimaster-r...,US Commercial Dev EastUS,20220401.0
863576,location-service-dev,2022-04-01 21:15:00,location-admin-uimaster-regression-69785b9b58-...,0.000000,0.0,0.0,0.000000,53551104.0,360468.0,location-service-dev_location-admin-uimaster-r...,US Commercial Dev EastUS,20220401.0
863577,location-service-dev,2022-04-01 21:20:00,location-admin-uimaster-reg                   ...,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN

checking if there are null values in data

In [14]:
df.filter(df.kubernetes_pod_cpu_usage_nanocores.isNull()).toPandas()

,namespace,timestamp,kubernetes_pod_name_keyword,kubernetes_pod_cpu_usage_node_pct,kubernetes_container_cpu_limit_cores,kubernetes_container_cpu_request_cores,kubernetes_pod_cpu_usage_limit_pct,kubernetes_pod_memory_usage_bytes,kubernetes_pod_cpu_usage_nanocores,key,environment_name,to_date
0,location-service-dev,2022-04-01 21:20:00,location-admin-uimaster-reg                   ...,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN

removing null values

In [15]:
df = df.filter(df.kubernetes_pod_cpu_usage_nanocores.isNotNull())

finding pod avg core

In [16]:
df_pod_core = df.groupBy('environment_name','namespace','kubernetes_pod_name_keyword').agg(avg("kubernetes_pod_cpu_usage_nanocores").alias('pod_avg_core'))

In [17]:
df_pod_core.orderBy("pod_avg_core",ascending=False).toPandas()

,environment_name,namespace,kubernetes_pod_name_keyword,pod_avg_core
0,US Commercial Dev EastUS,kube-system,image-verifier-594f6c777d-mz8zk,3.182920e+10
1,US Commercial Dev EastUS,cie-elastic,security-master-0,4.645744e+09
2,US Commercial Dev EastUS,cie-elastic,security-master-2,4.606738e+09
3,US Commercial Dev EastUS,cie-elastic,security-master-3,3.602780e+09
4,US Commercial Dev EastUS,cie-elastic,security-master-4,2.494615e+09
...,...,...,...,...
10436,US Commercial Dev EastUS,kuberhealthy,daemonset-daemonset-1648773722-1648773733-m6tl2,0.000000e+00
10437,US Commercial Dev EastUS,kuberhealthy,daemonset-daemonset-1648782721-1648782731-2vwb2,0.000000e+00
10438,US Commercial Dev EastUS,kuberhealthy,daemonset-daemonset-1648798022-1648798032-9fw6z,0.000000e+00
10439,US Commercial Dev EastUS,kuberhealthy,daemonset-daemonset-1648825921-1648825930-x9hst,0.000000e+00
10440,US Commercial Dev EastUS,kuberhealthy,daemonset-daemonset-1648834022-1648834033-7qlv6,0.000000e+00

finding total ns cores

In [18]:
df_ns_core = df_pod_core.groupBy('environment_name','namespace').agg(sum('pod_avg_core').alias('total_ns_cores')).orderBy('total_ns_cores',ascending=False)

In [19]:
df_ns_core.orderBy("total_ns_cores",ascending=False).toPandas()

             environment_name                namespace  total_ns_cores
0    US Commercial Dev EastUS              kube-system    5.021925e+10
1    US Commercial Dev EastUS              cie-elastic    4.448781e+10
2    US Commercial Dev EastUS                 ngdp-dev    3.201937e+10
3    US Commercial Dev EastUS             cadcloud-dev    3.113683e+10
4    US Commercial Dev EastUS         cie-security-dev    2.325072e+10
..                        ...                      ...             ...
143  US Commercial Dev EastUS      rwqm68-zap-task-dev    0.000000e+00
144  US Commercial Dev EastUS  astroupgrademanager-dev    0.000000e+00
145  US Commercial Dev EastUS                    vault    0.000000e+00
146  US Commercial Dev EastUS       bob-test-debug-dev    0.000000e+00
147  US Commercial Dev EastUS                   hkb483    0.000000e+00

[148 rows x 3 columns]

finding total cores

In [20]:
df_total_core = df_ns_core.groupBy('environment_name').agg(sum('total_ns_cores').alias('total_cores'))

In [21]:
df_total_core.toPandas()

           environment_name   total_cores
0  US Commercial Dev EastUS  3.943282e+11

joining both df

In [22]:
df_total_core = df_ns_core.join(df_total_core,['environment_name'],"left")

In [23]:
df_total_core.toPandas()

,environment_name,namespace,total_ns_cores,total_cores
0,US Commercial Dev EastUS,mercury-dev,1.538680e+07,3.943282e+11
1,US Commercial Dev EastUS,ngcmf-dev,1.378049e+09,3.943282e+11
2,US Commercial Dev EastUS,appsec-dev,1.161058e+10,3.943282e+11
3,US Commercial Dev EastUS,rwqm68,0.000000e+00,3.943282e+11
4,US Commercial Dev EastUS,acre-access-reviews-dev,1.261334e+07,3.943282e+11
...,...,...,...,...
143,US Commercial Dev EastUS,cad-webclient-dev,2.214246e+07,3.943282e+11
144,US Commercial Dev EastUS,hkb483,0.000000e+00,3.943282e+11
145,US Commercial Dev EastUS,avo-indoor-maps-dev,7.150861e+04,3.943282e+11
146,US Commercial Dev EastUS,eng-analytics-dev,4.421320e+07,3.943282e+11
147,US Commercial Dev EastUS,pronto-dev,1.640312e+07,3.943282e+11

finding ns percentage

In [24]:
df_ns_pct = df_total_core.withColumn("ns_percentage",df_total_core.total_ns_cores/df_total_core.total_cores*100)

In [30]:
df_req = df_ns_pct.select('environment_name','namespace','ns_percentage').orderBy('namespace')

In [31]:
df_req.toPandas()

             environment_name                  namespace  ns_percentage
0    US Commercial Dev EastUS                accnext-dev       0.057197
1    US Commercial Dev EastUS    acre-access-reviews-dev       0.003199
2    US Commercial Dev EastUS             alphasi500-dev       0.000000
3    US Commercial Dev EastUS                    ams-dev       0.054139
4    US Commercial Dev EastUS     analytics-services-dev       1.414295
..                        ...                        ...            ...
143  US Commercial Dev EastUS  virtualpartner-vulcan-dev       0.304303
144  US Commercial Dev EastUS                    vsa-dev       0.045009
145  US Commercial Dev EastUS  vsa-device-management-dev       0.089291
146  US Commercial Dev EastUS             vsa-devops-dev       0.002041
147  US Commercial Dev EastUS            vsa-sandbox-dev       0.016533

[148 rows x 3 columns]

joining df

In [34]:
df_req = df_req.join(df_env_cost,["environment_name"],"left")

In [35]:
df_req.toPandas()

,environment_name,namespace,ns_percentage,env_cost
0,US Commercial Dev EastUS,mercury-dev,0.003902,854.273649
1,US Commercial Dev EastUS,ngcmf-dev,0.349467,854.273649
2,US Commercial Dev EastUS,appsec-dev,2.944396,854.273649
3,US Commercial Dev EastUS,rwqm68,0.000000,854.273649
4,US Commercial Dev EastUS,acre-access-reviews-dev,0.003199,854.273649
...,...,...,...,...
143,US Commercial Dev EastUS,cad-webclient-dev,0.005615,854.273649
144,US Commercial Dev EastUS,hkb483,0.000000,854.273649
145,US Commercial Dev EastUS,avo-indoor-maps-dev,0.000018,854.273649
146,US Commercial Dev EastUS,eng-analytics-dev,0.011212,854.273649
147,US Commercial Dev EastUS,pronto-dev,0.004160,854.273649

req cost distribution ns cost

In [36]:
df_req = df_req.withColumn("ns_cost",df_req.ns_percentage*df_req.env_cost/100)

In [43]:
df_req.select('namespace','ns_percentage','ns_cost').toPandas()

                   namespace  ns_percentage    ns_cost
0                mercury-dev       0.003902   0.033334
1                  ngcmf-dev       0.349467   2.985408
2                 appsec-dev       2.944396  25.153201
3                     rwqm68       0.000000   0.000000
4    acre-access-reviews-dev       0.003199   0.027326
..                       ...            ...        ...
143        cad-webclient-dev       0.005615   0.047969
144                   hkb483       0.000000   0.000000
145      avo-indoor-maps-dev       0.000018   0.000155
146        eng-analytics-dev       0.011212   0.095784
147               pronto-dev       0.004160   0.035536

[148 rows x 3 columns]

###################################################################